services:
  - type: web
    name: mentivio
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/train_model.py
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1