services:
  - type: web
    name: mentivio
    env: python
    plan: free
    buildCommand: cd backend && pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: cd backend && gunicorn backend.app:app   
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.4"
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: assessment_data
          property: connectionString
      - key: ENCRYPT_SENSITIVE_DATA
        value: "true"
      - key: RENDER
        value: "true"