
services:
  - type: web
    name: mentivio
    env: python
    plan: free
    buildCommand: |
     # Use a supported Python version
      pyenv install 3.12.4
      pyenv global 3.12.4
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: |
      # python train_model.py  
      #python app.py    
      gunicorn app:app     
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: assessment_data
          property: connectionString
      - key: ENCRYPT_SENSITIVE_DATA
        value: "true"
      - key: RENDER
        value: "true"