services:
  - type: web
    name: mentivio
    env: python
    plan: free
    buildCommand:
      pip install --upgrade pip
      pip install -r requirements.txt
      python train_model.py
    startCommand: gunicorn app:app